Simon-Initiative/authoring-client

package.json

tick version for hotfix

---

src/components/sidebar/ContextAwareSidebar.tsx

This PR adds in the resource id into the sidebar display.
RISK: Low

include id in sidebar

---

package.json
src/data/persistence.ts
src/data/persistence/analytics.ts
src/editors/document/course/CourseEditor.scss
src/editors/document/course/CourseEditor.tsx

Depends on authoring-server branch
On the front-end side, this PR just adds a button to trigger the download on the backend.
The button only shows if the course has a dataset in the "done" state - ie not failed or processing.
Risk: Low
Stability: Stable

Authoring 1872 download dataset

---

src/editors/content/learning/VideoEditor.tsx

This PR restores the ability to change the video source.
RISK: Low, isolated to just the video editor component
STABILITY: High, tested and it works

allow source change

---

package-lock.json
package.json
src/utils/date.ts
test/utils/date-test.ts
yarn.lock

RISK: Low, Jest tests that will not affect deployed site
STABILITY: High, should enhance stability by  catching errors caused by changes to future date code

Add date unit tests

---

package.json
src/editors/content/learning/XrefEditor.tsx
src/editors/content/learning/contiguoustext/ContiguousTextToolbar.tsx

This PR is a re-application of Kyle's WBP fixes.  The original branch was polluted with style changes to the Navigation panel - which revert the current UI.
I've reviewed these changes and have approved them, they just need to be approved and merged

Xref editor fixes

---

src/editors/content/feedback/likertseries/QuestionTable.tsx
src/editors/content/feedback/singlelikertquestion/LikertEditor.tsx

This PR reapplies the lost even likert change.
RISK: Low,

reapply even likert changes

---

src/editors/content/learning/XrefEditor.tsx

This fixes a rendering issue where the type of xref target would not be updated in the editor sidebar.  
All changes made to learning/XrefEditor.tsx
RISK: Low - all changes made to lifecycle methods for xref editor

Authoring 2058 xref cleared

---

src/data/models/workbook.ts

This PR flips the order of bibliography and dependencies in a serialized WBP so that it conforms with the DTD.
RISK: Low

transpose bib and dependencies

---

src/editors/content/learning/LinkEditor.tsx

**Problem**:
Editing link href in the sidebar loses focus on every keystroke.
**To reproduce:**
Simply create a link and edit the href.  
**Solution:**
There was no easy fix for this, due to how we are routing edits for inline entities back through the editor component.  To workaround the problem, I made link editing stateful - and then only at the end of editing do we update the model. 
**Wireframe / Screenshot if UI work:**
None.
**Risk:**
Low. Isolated change.
**Areas of concern:**
None.

workaround focus problem

---

src/editors/content/learning/contiguoustext/render/styles.scss

Remove padding from last paragraph

0.37.0 - Slate paragraph padding

---

src/app.tsx

The redux logging console option must have been removed at some point

0.38.0 - Add redux logging option to local storage

---

src/data/persistence/webcontent.ts
src/editors/content/media/manager/MediaManager.tsx

**DEPENDS ON**: https://github.com/Simon-Initiative/authoring-server/pull/57
This PR fixes an issue with Edge image uploads failing. It also addresses an issue where the last uploaded image is not selected automatically, which is the most common use case.
**Risk**: Low. Only touches webcontent and media manager code
**Stability**: Tested on Edge, Chrome and Firefox and is stable

fix issue with edge uploads and selection

---

package.json
src/data/content/assessment/question.ts
src/editors/content/common/ContentTitle.tsx
src/editors/content/question/question/Question.tsx
src/editors/content/question/question/QuestionEditor.tsx
src/editors/document/assessment/AssessmentEditor.tsx
src/editors/document/common/questions.tsx
src/editors/document/feedback/FeedbackEditor.tsx
src/editors/document/pool/PoolEditor.tsx
yarn.lock

Copy and paste functionality of questions between assessments or courses.
https://olidev.atlassian.net/projects/AUTHORING/issues/AUTHORING-2234?filter=allopenissues&orderby=priority%20DESC&keyword=copy%20question

AUTH-2234: allow question migration between assessments/courses

---

package.json
src/components/Header.tsx
src/components/objectives/ObjectiveSkillView.tsx

This PR changes the link to the quick start help guide to use Freshdesk
RISK: Low

Authoring 2130 url

---

package.json

Version uptick for AUTHORING-2269-image_hotspot-fix hot fix

version uptick

---

package.json
src/actions/orgs.tsx
src/editors/document/org/OrgDetailsEditor.tsx

Had bug in change handling; now fixed.

move unitsonly warning from OrgDetailsEditor 

---

src/editors/content/part/NumericMatchOptions.bs.js
src/editors/content/part/NumericMatchOptions.re

This PR resolves an issue where an author was unable to use variables in a range for input type questions
Closes [AUTHORING-2282](https://olidev.atlassian.net/browse/AUTHORING-2282)
**Risk**: Low, only affects the Numeric Match options
**Stability**: Tested and is stable

fix an issue where varaibles werent persisting in range

---

package.json
src/data/content/learning/codeblock.ts

This PR adds CDATA content as "source" for codeblock editor

add cdata as source for codeblocks

---

package.json

uptick version

---

src/data/content/learning/figure.ts

This PR fixes the issue outlined in AUTHORING-2315 https://olidev.atlassian.net/browse/AUTHORING-2315

fix wbinline inside figure issue

---

.prettierrc
index.html
package.json
src/components/Header.tsx

For clearer communication with users, this changes the app header and page title to "OLI Echo".
This goes together with a PR to authoring-production in addressing AUTHORING-2327 by clarifying initial emails. However the two PRS are technically independent and could be deployed separately.

Use 'OLI Echo' in app header and browser tab

---

index.html
package.json

Latest version of mathlive breaks math field initialization.

pin mathlive version to 0.54
