Simon-Initiative/authoring-client

src/components/DeleteResourceModal.controller.ts
src/components/NavigationPanel.tsx
src/editors/document/org/OrgComponentEditor.tsx
src/editors/document/org/OrgDetailsEditor.controller.ts

This PR improves the workflow for deleting orgs.  
1) First, it ensures that deleted orgs are not displayed in the dropdown.
2) It also displays a different org after one is deleted
3) Finally, it removes the redundant (and non-functioning) "Remove Organization" button

Authoring 1884 org delete

---

src/editors/document/assessment/outline/tabs.tsx

This PR fixes the crash that occurs if a user removes all blocks from supporting content in an assessment. 
RISK: Low
STABILITY: High, tested and fixes the issue

handle no blocks correctly

---

src/components/WritelockModal.controller.ts
src/components/WritelockModal.tsx
src/components/objectives/ObjectiveSkillView.controller.ts
src/components/objectives/ObjectiveSkillView.tsx
src/utils/error.tsx

Show a modal / banner when an edit cannot be performed on the learning objective page (due to write lock, timeout).
We were previously trying to show a banner when the page was locked, but it wasn't showing up because the "scope" of the banner message wasn't correct.
Risk: low
Stability: stable

Show errors when the learning objective page is locked

---

package.json
src/actions/view.ts
src/components/Header.tsx

I also changed the `ViewActions` type because it was missing two routes we had added later
risk: very low
stability: stable

Make the course title in the header a link

---

src/components/objectives/ObjectiveSkillView.tsx
src/editors/document/org/Analytics.tsx
src/types/questionRef.ts

This PR further optimizes the rendering of the Objectives editor. It does so via two specific changes:
1. Reduce the algorithmic runtime of the reduceSkillToQuestionRefs method by calculating a mapping of skills to assessments that tag them, upfront.  This calculation was being inside a per skill loop, previously.
2. Make the parsing of body and parts of question refs "just in time" - rather than upfront.  This greatly improves the performance as neither of these are being used in this view - yet they were being calculated.
RISK: Low
STABILITY: High - a build is present on shattrath.  The  A&P course now renders in just a couple of seconds.

Authoring 1903 reduce

---

src/editors/content/learning/ImageEditor.tsx

After you've uploaded an image to a resource, it's hard to know what the image name is unless you go into the media manager and try to find it, but the manager itself doesn't always properly select the active image.
This PR just adds the filename (image path) to the sidebar so you know what image you've got uploaded. I'd like to fix the issue with the media manager not always selecting the image, but after some investigation, I found that the unhappy path that causes this issue is rare - it only applies to images that were uploaded pre-editor with filenames that include non-url-encoded characters (like spaces).
Risk: very low
Stability: stable

Add image filename to sidebar

---

package.json
src/data/content/assessment/pool.ts
test/data/models/full-test.ts
test/data/models/pool-with-sections.json

This PR handles pools with sections in a more correct fashion.  Instead of considering the section and the questions beneath it as "unsupported" the pool content wrapper now passes thru sections to get to the contained questions.
RISK: Low
STABILITY: Medium/High - the unit test works on a file that was breaking in production, but this hasn't been interactively tested in a real course

handle sections within pools

---

package.json
src/data/content/assessment/choice.ts

This PR allows MathML to be included in formative multiple question choice elements.
There is a bit of code in choice.ts that strips out a paragraph from single entry choice elements. If MathML was present in that paragraph this leads to a persistence error since the DTD requires MathML to be inside of a paragraph.
RISK: Low
STABILITY: High, without this fix adding MathML triggers the save error, with this fix one can add MathML

Authoring 1909 choice mathml

---

src/editors/content/common/draft/decorators/Extra.tsx
src/editors/content/container/connectEditor.ts

I still do not know what changed to break this, but explicitly inserting another Provider component restores the rollover editing functionality. 
RISK: Low
STABILITY: High, rollovers are now editable again

include an explicit Provider wrapper

---

src/data/models/workbook.ts

This PR adjusts logic in the WBP model to only serialize the bib:entries element if there are bib entries.  This prevents the resultant XML from containing an empty bib:file - which OLI is rendering as an empty "References" section
RISK: Low, isolated and well understood
STABILITY: High, tested and fixes the issue.

only include bib if there are entries

---

src/editors/document/org/OrgDetailsEditor.tsx

This PR addresses the issue of hardcoded 'Modules' in the warning message by simply making the message title and text dynamic and including the custom label.
Note, we reworded the title and message slightly to avoid having to pluralize the custom term, since it is conceivable that a user could be using a term that isn't pluralized by simply adding an 's' to the end.
RISK: Low
STABILITY:  High, we tested this change in the browser and it works.

Authoring 1850 no modules

---

src/data/persistence.ts
src/data/persistence/package.ts
src/editors/document/course/CourseEditor.tsx

This PR changes the theme selection UI to incorporate screen shots of each theme and a bit of description text, explaining what a theme is. 
This work depends on corresponding branches in server, dev, and production repositories. 
It also depends on the theme images being present in /oli/assets.  
RISK: Low

incorporate theme images into ui

---

package.json
src/editors/content/learning/AlternativeEditor.tsx
src/editors/content/learning/AlternativesEditor.tsx

- user can edit the Title via 
(a) a <TitleTextEditor
(b) the Sidebar Editor
- this is not the ideal solution, as discussed [here](https://olidev.atlassian.net/browse/AUTHORING-1974?atlOrigin=eyJpIjoiOTFjYTU4NzhjODJjNDZmODkwMzgzYTBhZDgzOTY4MzQiLCJwIjoiaiJ9)
- there is a slight bug where editing the Value will change the Title, but this is avoidable
RISK: Low -- changes contained to a single file
STABILITY: High -- no unit tests, but is a relatively consistent change

HOTFIX -- 1974 - user can edit the Title for an Alternative object

---

src/Main.tsx
src/components/NavigationPanel.controller.ts
src/components/NavigationPanel.tsx
src/components/OrgLibrary.tsx
src/components/PasteFailModalElement.tsx
src/components/ResourceView.tsx
src/data/models/utils/org.ts
src/editors/document/course/CourseEditor.controller.ts
src/editors/document/course/CourseEditor.tsx
src/editors/document/org/TreeNode.tsx

This PR simplifies the navigation panel in the following ways:
1) Renames first two tabs to "Course Details" and "Learning Objectives" 
2) Moves the "All resources" tab to a tab on the Course editor page. 
3) Removes the Organization dropdown component - and replaces it with the OrgLibrary component, now a tab on the CourseEditor view.
RISK: Low/Medium - Some non-trivial structural changes across a few key components in the system 
STABILITY: High, tested and seems to be working nicely

Authoring 1985 simplify

---

src/components/CoursesViewSearchable.tsx
src/data/types.ts
src/editors/manager/persistence/AbstractPersistenceStrategy.ts

Fix:
- Course IDs showing up as undefined in the all courses list
- Course resources were not properly locked
This code is refactored in the resource ID PR, but this temporary fix will work until that is merged.
Risk: low
Stability: stable

Fix course IDs showing as "undefined" in course list, fix resource locking

---

src/components/sidebar/ContextAwareSidebar.tsx

This PR tightens the check in CWRP.  Since every edits changes the 'lastUpdated' date on the resource, on *any* edit to the resource the refs were being refetched.  
This changes only updates if the course or resource actually *switches* to a different course or resource.
RISK: Low

adjust update logic

---

src/components/OrgLibrary.tsx

This PR fixes the problem of clicking on the active org in the org library and it routing the user back to the main view.
Fix was to ensure a valid handler was in place, instead of 'undefined'.
RISK: Low, isolated to org library
STABILITY: High, tested and fixes the problem

fix link click error

---

src/components/sidebar/ContextAwareSidebar.tsx

This fixes the flickering sidebar refs display.
All that was needed was to remove the CWRPs - the call to fetchRefs here never matters as anytime the course or resource changes the entire sidebar component is torn down and replaced
RISK: Low
STABILITY: High, fixes the problem

remove CWRPs

---

src/data/content/learning/draft/todraft.ts
src/editors/content/common/AbstractContentEditor.tsx
src/editors/content/common/RichTextEditor.tsx
src/editors/content/common/draft/DraftWrapper.tsx
src/editors/content/common/draft/decorators/Cite.tsx
src/editors/content/learning/blockcode/BlockCodeEditor.tsx
src/editors/content/learning/blockformula/BlockFormulaEditor.tsx
src/editors/content/learning/blockquote/BlockQuoteEditor.tsx
src/editors/content/learning/contiguoustext/ContiguousTextEditor.controller.ts
src/editors/content/learning/contiguoustext/ContiguousTextEditor.tsx
src/editors/content/learning/contiguoustext/ContiguousTextToolbar.controller.ts
src/editors/content/learning/contiguoustext/ContiguousTextViewer.tsx
src/editors/content/learning/contiguoustext/TitleTextEditor.tsx

There were a couple of problems leading to this bug.  First and foremost, the Cite decorator was a Redux connected component.  We have found that something with the migration to React 16.8 has broken the ability for Draft decorators to be able to render correctly when they are a connected component.  I refactored to make the CTE parent component fetch the orderedIds state.
Second, the todraft.ts was not accounting for cite entries that contained a single space as their content.  
RISK: Low/Medium, in theory could introduce perf issues with rendering, does not seem to have
STABILITY: High, seems to fix the issue

avoid connected decorator

---

package.json
src/editors/content/feedback/likertseries/QuestionTable.tsx
src/editors/content/feedback/singlelikertquestion/LikertEditor.tsx

This PR reapplies likert even numbers as a hotfix.
RISK: Low
STABILITY: High - the backend PR has already landed to master as part of sprint 32. This simply restores the front-end piece that adds the options

Authoring 2018 likert hotfix

---

src/components/sidebar/ContextAwareSidebar.tsx

This PR addresses AUTHORING-2036, 2025,  and 2043.  It removes deleted references, duplicate references, and sorts the references by type and title.
Only ContextAwareSidebar has changed.
This needs tested with larger, older courses to verify that the [Error loading page title] references we saw in Monday's session is gone.
STABILITY: high - only one file changed
RISK: Low

Authoring 2043 reference error

---

src/editors/content/question/imagehotspot/CircleEditor.tsx
src/editors/content/question/imagehotspot/RectangleEditor.tsx

**Business need**: Hotspots can be dragged outside of the allowable area in the editor, leading to course errors on publish. Users ran into this during learnlab
**Solution**: Constrain both the circle and rectangle hotspots within the editable "field" so they can't have edges outside of the allowed area
**Wireframe**: None
**Risk**: Low
**Areas of concern**: None, only affects image hotspot questions. Tested on shattrath by full-previewing courses after trying to move both rectangle and circle hotspots outside of the allowed area in each corner.

Prevent hotspots from being created outside of the allowed area

---

package.json
src/editors/document/course/CourseEditor.tsx

**Business need**: We received feedback from multiple people in the summer session that it was difficult to figure out what the **Team members** field on the course package home page was for and how to add users. 
**Solution**: A description above the typeahead component should help out.
**Wireframe**: None
**Risk**: Very low
**Areas of concern**: None, only a text change

Add team members description

---

package.json
src/components/objectives/ObjectiveSkillView.tsx

**Business need**: Some users in summer school were seeing the frowny face on the objective skill view page because of the `getFlattenedResources` method.
**Solution**: I'm not sure what the root cause is, but it seems like the `selectedOrganization` is sometimes undefined if it's not set in redux before the component is loaded. This should at least prevent the page from throwing.
**Wireframe**: None
**Risk**: Low
**Areas of concern**: Only the objective skill view editor changed

Fix error thrown sometimes on objective skill view

---

src/Main.tsx
src/components/CreateCourseView.tsx

**Business Need**: If a user creates a new course with a title that has a long first word, resources that use the course ID will cause DB errors when saved. This has been seen multiple times when creating new organizations, which create IDs based on the course ID.
**Solution**: 
1) When creating courses, slice the length of the first word in the title that's used to create the package ID to 16 characters, then append the unique GUID to the ID.
Also remove non-alphanumeric characters from the title when creating the ID.
2) Slice the length of new organization IDs to 40 chars.
These lengths are conservative (resource IDs can be up to about 60 chars in total), but longer IDs don't really serve much of a purpose beyond ensuring uniqueness, which isn't an issue when resource IDs only need to …

Limit package id and org id lengths

---

src/editors/document/assessment/AssessmentEditor.tsx

**Problem**:
If you add questions in succession after converting to a branching assessment and don't refresh the page, the content you add to the new questions won't save.
To reproduce:
1) Create new formative assessment
2) Convert to branching
3) Add two more questions
4) Add content to the active (third) question
5) Open the first question
6) Go back to the last question and notice that the content is missing
**Solution**:
Very simple once I figured it out - when you add a question node, it updates the assessment model with a new page and sets the active page in redux. The redux action was dispatching before the assessment model had been updated with the new page, so any changes to newly added questions weren't being saved to the page.
I moved the redux action into the `onEdit` callback …

Fix data loss on branching assessment toggle

---

package.json
src/reducers/documents.ts

**Problem**:
Regression bug - multiple choice correct answers could not be changed. a TSMonad stack overflow triggered whenever setting a different answer as correct.
**Solution**:
Something with our TSMonad library is causing issues with our app. I don't fully understand the problem, but through trial and error I was able to refactor the `setCurrentNodeOrPage` reducer to fix the issue.
None.
**Risk**:
Very low, no logic changes, just code structure.
None, aside from the fact that I don't understand the root cause.

Fix multiple choice correct answer selection

---

src/components/CoursesViewSearchable.scss

Something messed up the styling of the buttons on the CoursesViewSearchable page.
Before:
After:

Fix courses view styling

---

package.json
src/components/ResourceView.tsx
src/components/common/SearchBarLogic.tsx
src/components/objectives/InlineEdit.tsx
src/components/objectives/Objective.tsx
src/components/objectives/ObjectiveSkillView.scss
src/components/objectives/ObjectiveSkillView.tsx
src/components/objectives/Skill.tsx

**Problem**:
Learning engineers have no easy way to match skill IDs downloaded from the editor (on the Course Overview page and from the Data Analytics page) to actual skills and the questions they're attached to. 
**Solution**:
1) Add searching by ID on the learning objective/skill page
2) Add ability to display IDs on learning objective/skill page
3) Make links to questions on learning objective/skill page openable in new tab
4) Make "all resources" table copyable and able to open links to resources in new tab
**Risk**:
Low, mostly affects display.
None.

0.34.2 - Add skill/LO features for learning engineers

---

src/components/toolbar/ToolbarButton.tsx

I'm proposing that we get rid of the delay on the toolbar button tooltip help text. When we originally set up the resource toolbars, we were worried that if the tooltips showed up immediately on hover it would feel "spammy." But now that we have so many insert and formatting options I feel that that concern is far outweighed by the difficulty of figuring out what each button actually does.
Most other editors (google docs, apple pages, etc.) have an initial delay of about a second before a tooltip shows up, and then any other button you hover over continues to show tooltips after that initial delay was met. In our editor, we don't have a simple way of enabling a "common" delay for all tooltips, so I think the best thing to do is just get rid of the delay on button tooltips so people can …

0.36.0 - Change toolbar button tooltip delay

---

src/data/content/learning/slate/toslate.ts
src/editors/document/analytics/Analytics.tsx

**Problem**:
Expanding analytics data for objectives that reference an input question throws an error.
**Solution**:
When the slate model is parsed, it assumes `backingTextProvider` is defined, so it throws an error when null. That variable is used to select the input question type, which doesn't matter on the Analytics page since we're just getting the question stem text. So it's fine to just default to a numeric question and continue getting the text.
None.
**Risk**:
Low. I also refactored some of the `Analytics` logic when testing since I couldn't tell if it was working properly.
None.

0.37.0 - Fix thrown error on objectives page

---

src/editors/content/learning/contiguoustext/render/InputRefDisplay.tsx

**Problem**:
Dropdown input elements cannot be selected in Firefox after being inserted into a question. The issue was that Firefox does not support the `onClick` handler in `<select>` elements, so the selection was never getting triggered. 
**Solution**:
Change the `<select>` element to an `<input>`. The look and feel is a little different - I added a placeholder text to signal that it's a dropdown and not a normal input, but I'm open to suggestions if we want to present it in a different way.
None.
**Risk**:
Low.
None.

0.37.0 - Fix Firefox Dropdown Input Selection

---

src/editors/content/container/ContentContainer.tsx
src/editors/content/learning/contiguoustext/utils.tsx

**Problem**:
Inserting content into a workbook page can fail when a content decorator is selected because the insert logic does not take into account the case when no text is selected. The logic falls through to the base case which splits text rather than inserting the item after the selected decorator.
**Solution**:
Support the case when a content decorator is selected by checking if there is a "focused" text selection.
None.
**Risk**:
Low.
None.

0.37.0 - Fix inserting items when selecting content decorator

---

src/reducers/documents.ts

**Problem**:
Regression - toggling a branching assessment without a page refresh causes data loss when continuing to edit questions.
Steps to reproduce:
1. In echo, create a new formative assessment.
2. Flip the switch to make it a branching assessment.
3. Add a second and third multiple choice question and try to add text to the prompts/answers.
4. Wait for "All changes saved" in the top-right.
5. Leave the question and come back to it. The text will be gone 
**Solution**:
The `setCurrentNodeOrPage` reducer function was incorrect and didn't find the right node when adding questions that result in new pages being created, which is the case for branching assessments.
None.
**Risk**:
Low.
None.

0.37.0 - Fix selecting the correct node when toggling branching assessment

---

src/components/toolbar/InsertToolbar.tsx

**Problem**:
This PR was part of a larger investigation to ensure our text insertion and splitting logic was correct, and the main issue is fixed as part of `AUTHORING-2148`. This PR has a separate smaller piece, which is to prevent `ContiguousText` insertion when a paragraph element is currently selected.
**Solution**:
Check if the actively selected item is a paragraph and prevent inserting another text block if so.
None.
**Risk**:
Low.
None.

0.37.0 - Prevent text insertion when selecting text

---

src/editors/content/container/ContentContainer.tsx
src/editors/content/learning/contiguoustext/ContiguousTextEditor.tsx
src/editors/content/learning/contiguoustext/utils.tsx

**Problem**:
The editor could get into weird states from inserting items from the toolbar when contiguous text or content decorators were selected.
Cases not handled correctly:
1. Cursor at beginning of contiguous text
2. Cursor at end of contiguous text
3. Only content decorator selected, no text focus
4. Cursor inside contiguous text, then selecting another contiguous text block's content decorator
**Solution**:
1. Update slate utils to identify when cursor is at beginning or end of contiguous text block
2. Reset the active editor when a content decorator is selected
3. Stop broadcasting slate changes when an editor instance is de-selected (by checking `isFocused`)
None.
**Risk**:
Medium - core text editing logic.
None.

0.37.0 - Fix toolbar insertion issue when selecting text

---

package.json
src/data/models/course.ts
src/editors/content/container/ToolbarContentContainer.tsx
src/editors/content/learning/contiguoustext/ContiguousTextToolbar.tsx
src/editors/document/course/CourseEditor.tsx

server branch: same name, `language-hotfix`
Deploying courses causes a build error.
The main change is to go from saving the default/chosen foreign language from the language element on the content_package table and XML to a new misc JSON field in the database. The client had to be changed to use this new field.

Fix language attribute usage

---

src/data/content/learning/slate/topersistence.ts

**Problem**:
This is a fairly serious problem where if a slate `inline` is saved with empty text content, it can cause the course build to fail. For example, OLI validates links to make sure they have a clickable "target" text, but Echo has no problem saving link elements with empty child text.
To reproduce:
1. Highlight text in a workbook page
2. Use the toolbar to create a `link` with the selection
3. Reselect the link text
4. Delete the text
5. Wait for the changes to propagate to SVN and then full preview the course
**Solution**:
Don't save content-based inlines with empty text contents. Content-based inlines are the code-highlighted inlines in this list:
- `Link`
- `Xref`
- `ActivityLink`
- `Quote`
- `Code`
- Cite
- Command
- Math
- Extra
- Image
- Sym
- InputRef …

0.38.0 - Fix inlines breaking course build when text content is empty

---

src/components/GlobalError.tsx

It doesn't seem like the `GlobalError` component was actually displaying the thrown error that caused it to trigger. It is showing subsequent errors (like React's "this error was caused by the x component.")

0.38.0 - Add console log for errors that are caught

---

src/editors/document/org/OrgComponentEditor.tsx

**Problem**:
When viewing analytics for an org component (unit, module, section), the page flickers pretty badly and new requests for new analytics data keep being made.
There are two separate issues here:
1. `componentWillReceiveProps` in `OrgComponentEditor` was using the reference equality operator on two `Maybe`s, so the `findComponentModel` kept running
2. Some higher level component keeps creating a new organization model and passing it down to this component, so looking inside the `Maybe`s to compare the organization model itself wasn't working
**Solution**:
Issue #1 was simple to fix. For issue #2, I spent a fair amount of time tracking down why the organization model kept being re-created and passed down to the `OrgComponentEditor`. I ended up touching a lot of different heavily …

0.38.0 - Fix organization component analytics refresh issue

---

src/data/content/assessment/question.ts
test/data/content/assessment/input-numeric-test.ts
test/data/content/assessment/questions-invalid/input-numeric-match-star.json
test/data/content/assessment/questions-valid/input-numeric-match-star.json

**Problem**:
See Jira ticket for more info:
https://olidev.atlassian.net/browse/AUTHORING-2170
OLI supports numeric input question with multiple correct answers, but Echo doesn't. This is necessary for one of the courses that the learning engineers are migrating to Echo.
The problem in the code is that when "catch-all" responses are created for generic incorrect feedback (using the `match: '*'` attribute), they sometimes get inserted into the middle of the `Responses` map on the `Part`. These are persisted in order, and when OLI goes to create the question, it sees the `match: '*'` and disregards any targeted feedback in the responses following it.
_To reproduce:_
1. Create an assessment (formative or summative) with a numeric input question
2. Create two "correct" answers, each with a …

0.38.0 - Enable numeric input questions to have multiple correct answers

---

src/reducers/documents.ts

https://olidev.atlassian.net/browse/AUTHORING-2176
If you use the "simple select" feature on some assessment questions to select the correct answer rather than manually entering a score, you get the `monad stack overflow` error we keep seeing. I tracked down where it was throwing and it turned out to be in the `SetActiveNodeOrPage` clause of the `documents` reducer, where we've seen this issue before.
I changed each of the data structures used in the section that was failing to convert to plain javascript arrays instead of using immutable js, and it fixed the issue. But I don't understand why this part of the codebase keeps triggering that error.

0.38.0 - "Simple Select" on questions to select correct answer not working

---

src/editors/document/org/OrgComponentEditor.tsx

https://olidev.atlassian.net/browse/AUTHORING-2173
This PR is to fix a regression caused by another change on sprint 38. If you drag and drop organization components to re-order them, the new order doesn't show up in the main window. This was caused by a previous change in `componentWillReceiveProps` in the same component. I changed it to only update when a new organization ID was passed in through props to prevent the analytics page from constantly making new requests, but the organization ID is too narrow. If structural changes are made to the org (like re-arrangement), the ID will be the same but the reference to the organization resource will change, so I changed the comparison to check that instead.

0.38.0 - Re-arranging organization components not displaying in editor

---

package.json
src/editors/content/learning/contiguoustext/ContiguousTextEditor.tsx

This PR fixes the issue where on a large workbook page simply hovering one's mouse over different contiguous text editors causes focus changes and scrolling - leading to a "jumping around" effect that is quite distracting and annoying. 
The solution was to remove the re-render of the CTE when the hover changes. 
RISK: Low
STABILITY: High, tested locally and on shattrath

Authoring 2186 focus

---

src/data/content/metadata.ts
src/data/models/course.ts

**Problem**:
Several older courses that were recently brought into Echo cause errors when their package information (course title, description, etc.) is changed.
List of courses:
- Oracle 101
- Procurement Card Application
- Finance Fundamentals
- Purchase Card Refresher Training (CMU Finance)
An error was thrown when parsing the `preferences` on the package, which was initially used as part of the **Foreign** content item and thought to be the source of this problem.
**Solution**:
After investigating, there were actually three separate small problems, none of which were related to the **Foreign** element changes:
1. Echo was converting the package `preferences` to a string on the client
2. The server could not handle empty preferences objects
3. The `authors` field of package `Metadata` …

fix parsing metadata and prefs

---

package.json
src/data/content/learning/slate/toslate.ts

This PR fixes the ability to handle resources that contain empty inline markup elements, such as &lt;sub&gt;&lt;/sub&gt; or &lt;em style="italic" &gt;&lt;/em&gt; 
Currently the editor will not load resource that contains these types of elements. 
The solution here is to detect the empty element and simply ignore it.
STABILITY: High, tested locally with several pages that contain this issue and it fixes the problem.
RISK: Low/medium: fairly isolated, but this is in the core parsing code

ignore empty marks

---

src/editors/content/learning/repl/ReplEditor.tsx

This PR fixes and issue when creating a REPL activity in the editor, it will not have questions yet and therefore the REPL editor cannot determine what time of REPL to instantiate. This causes the REPL to show an error message making it unusable.
Steps to reproduce:
1. Create new REPL activity
2. Enter REPL activity
3. Exit, REPL activity and then reenter
REPLEditor should simply default to python, for now
**Risk**: Low, targeted
**Stability**: Tested, stable

HOTFIX 0.38.2: Fix REPL creation issue

---

package.json
src/data/content/learning/contiguous.ts
src/data/content/learning/slate/topersistence.ts
src/data/content/learning/slate/toslate.ts
src/editors/content/learning/contiguoustext/ContiguousTextToolbar.tsx
src/editors/content/learning/contiguoustext/render/render.tsx
src/editors/manager/persistence/DeferredPersistenceStrategy.ts

This PR fixes the fact that the editor is stripping out inline code elements from pages.
The root cause was how the blockcode type was not wired up correctly.  I took this opportunity to instead treat code inlines as marks, which simplifies the implementation.
I also added the ability to create code inlines via the toolbar (previously we called the "var" element "Code").
RISK: Medium
STABILITY: High, testing shows that it works

Authoring 2210 code

---

src/components/sidebar/ContextAwareSidebar.controller.ts
src/data/content/learning/contiguous.ts
src/editors/content/common/InputList.scss
src/editors/content/content/ContentEditor.scss
src/editors/content/feedback/common.scss
src/editors/content/learning/contiguoustext/ContiguousTextEditor.controller.ts
src/editors/content/learning/contiguoustext/ContiguousTextEditor.tsx
src/editors/content/part/ChoiceFeedback.scss
src/editors/content/part/Feedback.scss
src/editors/content/question/ordering/Ordering.scss
src/editors/content/question/question/QuestionEditor.scss
src/editors/document/assessment/AssessmentEditor.tsx
src/editors/document/common/questions.scss
src/editors/document/workbook/WorkbookPageEditor.tsx
src/reducers/active.ts

**Problem**:
Some assessment contiguous text editors cannot be selected in Safari, so the text cannot be edited.
Affects:
- supporting content
- choice text
- feedback text
**Solution**:
The `@include disable-select` mixin which sets the `user-select: none` on the `div`s surrounding the CTEs was preventing user selection. I removed the mixin from the areas with the problem.
I also made a small refactor to clean up the `active` reducer while I was trying to figure out what the issue was. Originally I thought the redux state might not be updated correctly, but that wasn't the problem.
None.
**Risk**:
Low - CSS changes, reducer refactor is small and was tested.
Not sure why this issue came up to begin with, the css properties have been set that …

HOTFIX 0.40.1 - Fix text editing in CTEs in Safari

---

package.json
src/editors/content/learning/repl/repl_assets.ts

This PR fixes an issue where REPL activities are embedded within Example and the width of the superactivity may be smaller than normal
**Risk**: Low, style only and only affects REPLs
**Stability**: Tested and is stable

HOTFIX 0.40.2 - AUTHORING-2222 fix REPL activity width

---

package.json

Uptick the version shown to users on the client for a server hotfix.
Also pin the Typescript version to 3.7.5 to prevent compilation errors from the new version.

HOTFIX 0.41.1 - Uptick Version for Server Change

---

package.json
src/components/objectives/ObjectiveSkillView.tsx

This PR applies a band-aid to skill editing to address a problem where skills with duplicate ids are getting added - which triggers a server side validation failure. 
The fix here assumes the problem is manifesting with a skill with a new guid, yet the same id.  So using the guid directly to update the skills collection would lead to a duplicate id.  Instead, we use the id of the updated model to find an existing skill.  
RISK: Low, tested locally and everything still works
STABILITY: Unknown if it provides full protection against the unknown root cause

prevent a duplicate skill from being created

---

package.json
src/components/objectives/ObjectiveSkillView.tsx

This PR does actually address the skill renaming issue.  Debuggin locally revealed that the internal guid of a skill was getting out of sync with the guid used as the key in the outer orderedmap.
This PR prevents that from happening by not using the guid of the supplied edited skill, but rather it reuses the one that it finds in the current map. 
I suspect this problem could occur for objectives as well, so I applied the fix there also.
RISK: Low, tested and works well
STABILITY: With the davis course imported locally i  no longer see this problem

keep guid and key in sync

---

src/actions/media.ts
src/components/objectives/ObjectiveSkillView.tsx
src/data/models/course.ts
src/editors/document/analytics/Analytics.tsx
src/types/edge.ts

This PR removes the "jsonObject" attribute from the Edge type "metadata" and "jsonObject" reference in the course package "metadata". Cleans up its usage of both in the rest of the code base.

Authoring 2257 empty preferences bug

---

package.json
src/components/resourceview/ResourceView.tsx

This PR addresses the problem that a pool can be created with an empty title, which breaks the build.
This fix simply disallows resource creation with empty titles. 
It does not adjust title editing from within a resource editor (like a work book page editor), since attempts there to edit a title to empty already fail with a red banner warning.  Therefore, creation via the "All Resources" view is the only way to trigger this condition of the build being broken.
RISK: Low

Authoring 2254 empty titles

---

package.json
src/components/CoursesViewSearchable.tsx

This PR addresses the problem of the sorting in the courses view page.  The root cause was simply that the array of comparators for the inner sorted table were out of order with respect to the parallel array of column renderers. 
RISK: Low, fix isolated to just this view
STABILITY: High, tested interactively and fixes the problem

Fix for authoring-2245 course sorting error

---

package.json
src/components/CoursesViewSearchable.tsx
src/components/Header.tsx

This bug proved to be harder to solve than initially thought. As it turns out the behavior of "failure to navigate" is non-deterministic in production - and completely unreproducible in my local dev environment.  What I believe it relates to is some timing issue with the list of course packages loading when visiting the "All Courses" view - and somehow that interleaving or interrupting the dispatch or receipt of a redux action that is designed to clear the global redux state of the "current course".
A bit of background: when you are in a course and when you navigate back to the "All courses" page, several actions are dispatched.  One of them is the action created by `enterApplicationView` in `src/actions/router.ts`, line 47.  This message is received in the course reducer …

Authoring 2296 switching

---

package.json
src/data/content/restrictions.ts
src/editors/content/learning/contiguoustext/ContiguousTextToolbar.tsx

This PR addresses citation issues by eliminating the problematic "Cite existing bib entry" feature.  This forces the issues to first create a bib entry, and then create a citation targeting that entry.
Also, this PR enables reordering of bib entries. This allows the user to workaround issues where they get citation numberings "out of order". 
Tested on shattrath.

Authoring 2321 citation

---

package.json
src/editors/document/analytics/Analytics.tsx

There's a problem when viewing analytics on some courses where the page will flicker and the analytics tab will constantly refresh as it re-renders. This is an attempt to fix that, though it's hard to test locally. The plan is to either deploy to Shattrath and get a course with a dataset up, or if not, deploy to Echo to keep an eye on and test (the changes are restricted to the analytics tab).
Changes:
`componentWillReceiveProps`: only consider changes when the `model` (the currently viewed organization item) has a different ID
`componentShouldUpdate`: only re-render when state changes or one of the "main" props change

Attempt to fix the analytics refresh issue when viewing analytics

---

package.json
src/data/content/learning/extra.ts

Extras tag is stripping off pronunciation and translation present in the original XML on persistence. This PR address that issue

fix extras persistance

---

src/data/content/learning/extra.ts

PR fixes a bug where multiple empty pronunciation or translation tags on a page use the same id value breaks XML validation

block empty pronunciation or translation tags

---

package.json
src/data/content/learning/slate/toslate.ts
test/data/models/li-no-paragraph-test.ts
test/data/models/li-no-paragraph.json

This adjusts content parser to handle the case of AUTHORING-2324 in which em-tagged text pieces within complex list items were getting deleted. It also adds a unit test for this case. 
The bug arose in the case of a list item containing some partially styled text along with a nested ul, without wrapping its content in a paragraph. A sample case:
```
<ul>
<li><em>Emphasized </em> OuterList Item
<ul >
<li>InnerItem</li>
</ul>
</li>
</ul>
```

Preserve em-styled text in list items without paragraphs

---

package.json
src/editors/content/media/manager/MediaManager.tsx

Adds a check against problem-causing characters in media filenames to upload. Adds error message area to MediaManager a la Torus media manager to display message.   
The build system prohibits colon, semi-colon, backslash and forward slash in filenames. Colon is prohibited on Windows but is evidently possible on recent MacOS.  Semi-colon is possible on any platform. Backslash and forward slash are prohibited on Windows but possible in filenames on MacOS.

prevent upload of media files with bad characters in names

---

package.json
src/data/content/learning/extra.ts
src/editors/content/learning/ExtraDefinitionEditor.tsx

Change to treat Extra's with only audio or translation but no meaning elements as Rollover Definitions. These occur in PIMA French XML. Need to treat as Definitions so can view/add/edit the translation or audio pieces.
One odd effect with this change is that if you load an Extra with translation only in the XML and clear the translation content, it now has no content to determine it to be a definition and reverts to being treated as Rollover Content, and you can't add translation back in. You just have to delete the anchor text and start a new Rollover Definition. Expect this will be rare. 
Also fix to properly save changes for the case of Rollover Content. Seems this had been broken since the rollover Definition editor was enhanced, apparently unnoticed.

edit Extra with audio or translation as definition. 

---

package.json
src/data/models/org.ts

Corrects a small coding error in organization fromPersistence. Error caused new guid to be set into the id field whenever loading an org model. Evidently did not affect very much  -- code initiating a load would already have the correct id in some variable so wouldn't need to fetch it from the corrupted model. But was responsible for AUTHORING-2329. URLS in page links on ResourceView picked up a bad orgId from the model, so opening a resource from resource view always caused reversion to default org.

Prevent org switch on loading page from resource view

---

package.json
src/editors/manager/EditorManager.tsx

This blocks saving a read-only document to fix endlessly looping in the "Session expired" popup that comes up on save failures due to missing lock. 
Fresh load of a document almost always triggers a save (as can be seen from the "all changes saved" message you get), apparently because the process of putting content into the slate editor generates change notifications. Code at the EditorManager level was not checking if document was read-only before saving. So once this popup came up, reloading from the "Refresh" button in the popup would trigger a repeat of the failure and popup.
With this change, if you open the document readonly the popup should not appear. If you open non-readonly and someone else acquires the lock during the session, an attempted change will get the popup once (which …

Prevent looping "session expired" popup on read-only pages

---

src/data/content/workbook/xref.ts
src/editors/content/learning/XrefEditor.tsx

This hides the target window choice in the xref sidebar, because the legacy delivery system doesn't handle this option (themes produce code to open xrefs in new medium-sized popup window).

Hide xref target window choice

---

index.html
package.json

This loads mathlive css files for mathlive version 0.50.7, matching the version used by delivery. Needed for proper rendering of the MathLive Preview widget shown when authoring a math input question. 
(The MathLive Preview component is shown to enable the author to use the same MathLive keyboard the students will see to construct a mathematical expression and then copy the generated LaTex for use as an answer match.)

load css files for pinned mathlive version

---

package.json
src/data/content/learning/contiguous.ts

This fixes a coding error which prevented Echo from finding the id for a cross-reference link to a TextBlock element on a page.   There is no JIRA issue for this, it was discovered while working on a different bug.

fix glitch preventing xref to text block element

---

package.json
src/editors/content/learning/XrefEditor.tsx

This adjusts the XRefEditor to prevent a situation in which invalid xrefs can wind up saved, breaking the package build. An invalid xref could be saved by (1) creating an xref to a particular element on a page, and then (2)changing the target page in the xref editor. The editor would display that the target is not found, but still write out an invalid xref to a target element that does not exist on the relevant page.
This changes the editor so that changing the page in this case resets the xref to link to the whole page until a new particular element target is set by the editor procedure. 
This also modifies the on-screen instructions to take out the instruction to open the target in a new tab, since opening in a new tab did not seem to work.

Prevent invalid xrefs from being saved

---

package.json
src/data/content/learning/slate/toslate.ts

This fixes the toSlate contiguous text parser to handle the case of cdata within a "mark", now being used for inline code. 
A couple of places in the code incorrectly assumed text would be in the "#text" attribute of a terminal mark (one with no subsidiary marks). But the text can be in EITHER a #text attribute OR a #cdata attribute, though the #cdata option was apparently not used before now.

fix toSlate parser to handle cdata inside mark (for code tag)
